version: '3.8'

services:
  app-relay-dashboard:
    image: daclong120/app-relay-dashboard:latest
    container_name: app-relay-dashboard
    restart: unless-stopped
    ports:
      - "3001:3000"
    env_file:
      - .env

  app-relay-worker:
    image: daclong120/app-relay-worker:latest
    container_name: app-relay-worker
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - app-relay-dashboard
